version: '2.4'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.9.0
    restart: always
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "opendistro_security.ssl.http.enabled=false"
      - node.ingest=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - network

  odfe-node2:
    image: amazon/opendistro-for-elasticsearch:1.9.0
    restart: always
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node2
      - discovery.seed_hosts=odfe-node1,odfe-node2
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "opendistro_security.ssl.http.enabled=false"
      - node.ingest=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9201:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - network

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.9.0
    restart: always
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://127.0.0.1:9201
      ELASTICSEARCH_HOSTS: http://127.0.0.1:9201
    network_mode: "host"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.7.1
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    expose:
      - "1514"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    network_mode: "host"

volumes:
  odfe-data1:
  odfe-data2:

networks:
  network:
